cargo-features = ["edition2024"]

[package]
name = "y"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "y"
path = "main.rs"

[features]
unstable-features = [] # for rust-analyzer

# Do not add any dependencies

[profile.dev]
debug = 1
